name: Build & Push Backend Image to ECR

on:
  push:
    branches: ["main"]
    paths:
      - "src/ApiService/**"
      - ".github/workflows/build-backend.yml"

jobs:
  authenticate:
    name: auth
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::422600867425:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Backend Image
        run: |
          IMAGE_URI=${{ secrets.BACKEND_REPOSITORY }}:latest
          echo "Building and pushing $IMAGE_URI..."
          docker build -t $IMAGE_URI ./src/ApiService
          docker push $IMAGE_URI
