name: Build & Push Frontend Image to ECR

on:
  push:
    branches: ["main"]
    paths:
      - "src/Frontend/**"
      - ".github/workflows/build-frontend.yml"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  FRONTEND_REPOSITORY: ${{ secrets.FRONTEND_REPOSITORY }}

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Frontend Image
        run: |
          IMAGE_URI=${{ env.FRONTEND_REPOSITORY }}:latest
          docker build -t $IMAGE_URI ./src/Frontend
          docker push $IMAGE_URI
