name: Build & Push Backend Image to ECR

on:
  push:
    branches: ["main"]
    paths:
      - "src/ApiService/**"
      - ".github/workflows/build-backend.yml"

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: üîç Debug OIDC Token
        run: |
          echo "Requesting GitHub OIDC token..."
          TOKEN=$(curl -sLS -X POST -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          if [ -z "$TOKEN" ]; then
            echo "‚ùå No se gener√≥ token OIDC"
            exit 1
          else
            echo "‚úÖ OIDC token emitido correctamente"
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::422600867425:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Backend Image
        run: |
          IMAGE_URI=${{ secrets.BACKEND_REPOSITORY }}:latest
          docker build -t $IMAGE_URI ./src/ApiService
          docker push $IMAGE_URI
