name: Build & Push Frontend Image to ECR

on:
  push:
    branches: ["main"]
    paths:
      - "src/Frontend/**"
      - ".github/workflows/build-frontend.yml"

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::422600867425:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Frontend Image
        run: |
          IMAGE_URI=${{ secrets.FRONTEND_REPOSITORY }}:latest
          docker build -t $IMAGE_URI ./src/Frontend
          docker push $IMAGE_URI
