name: Build & Push Backend Image to ECR

on:
  push:
    branches: ["main"]
    paths:
      - "src/ApiService/**"
      - ".github/workflows/build-backend.yml"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  BACKEND_REPOSITORY: ${{ secrets.BACKEND_REPOSITORY }}

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::422600867425:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Backend Image
        run: |
          IMAGE_URI=${{ env.BACKEND_REPOSITORY }}:latest
          echo "Building and pushing $IMAGE_URI..."
          docker build -t $IMAGE_URI ./src/ApiService
          docker push $IMAGE_URI
